In [1]:
%matplotlib inline


# Markov chains

Here we look at how to formulate expected threat in terms of a Markov chain.
First watch the video


..  youtube:: 5ESij-MDKl4
   :width: 640
   :height: 349


In [2]:
import numpy as np

## Setting up the matrix
We first set up the pass matrix *A* and the goal vector *g*.



In [3]:
#Pass matrix
A = np.matrix([[0.25, 0.20, 0.1], [0.1, 0.25, 0.2],[0.1, 0.1, 0.25]])
#Goal vector
g = np.transpose(np.matrix([0.05, 0.15, 0.05]))

## 1- Linear algebra method

Here we solve *(I-A)xT = g*



In [4]:
xT1 = np.linalg.solve(np.identity(3) - A,g)

print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT1))

Expected Threat
Central, Box, Wing
[[0.14991763 0.25205931 0.12026359]]


## 2- Iterative method

Here we iterate xT' = A xT + g
to update through each move of the ball



In [5]:
xT2=np.zeros((3,1))            
for t in range(10):
   #print(np.matmul(A,xT2) + g)
   xT2 = np.matmul(A,xT2) + g

print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT2))

Expected Threat
Central, Box, Wing
[[0.14966911 0.25182476 0.12007973]]


## 3- Simulation method

Here we simulate *num_sim* possessions, starting from each of the three areas.



In [12]:
num_sims=500
xT3=np.zeros(3) 

description = {0: 'Central', 1: 'Wing', 2: 'Box' }

for i in range(3):
    num_goals = 0

    print('---------------')
    print('Start from ' + description[i] )
    print('---------------')

    for n in range(num_sims):
        
        ballinplay=True
        #Initial state is i
        s = i
        describe_possession=''
        
        while ballinplay:
            r=np.random.rand()
            
            # Make commentary text
            describe_possession = describe_possession + ' - ' + description[s]
            
            
            #Cumulative sum of in play probabilities
            c_sum=np.cumsum(A[s,:])
            new_s = np.sum(r>c_sum)  
            if new_s>2:
                #Ball is either goal or out of play
                ballinplay=False
                if r < g[s] + c_sum[0,2]:
                    #Its a goal!
                    num_goals = num_goals + 1
                    describe_possession = describe_possession + ' - Goal!'
                else:
                    describe_possession = describe_possession + ' - Out of play'
            s = new_s  
            
        #print(describe_possession)  
            
    xT3[i] = num_goals/num_sims


print('\n\n---------------')
print('Expected Threat')
print('Central, Box, Wing')
print(xT3)

---------------
Start from Central
---------------
---------------
Start from Wing
---------------
---------------
Start from Box
---------------


---------------
Expected Threat
Central, Box, Wing
[0.122 0.256 0.132]


Here I work through the derivation of equations for *xT*

<img src="file://../../../source/images/lesson4/DeriveMarkov1.png">

Here I outline how we write this in matrix form:

<img src="file://../../../source/images/lesson4/DeriveMarkov2.png">

